import Head from "next/head";
import Image from "next/image";
import BannerComponent from "@/components/BannerComponent";
import axios from "axios";
import { useEffect, useState } from "react";
import Header from "@/components/Header/Header";
import "../styles/global.scss";
import Footer from "@/components/Footer/Footer";
import ServicesComponent from "@/components/ServicesComponent/ServicesComponent";
import ModulesBlock from "@/components/ModulesBlock/ModulesBlock";
const qs = require("qs");
export default function Home({ strapiData }) {
  const [data, setData] = useState([]);

  const getData = async () => {
    const query = qs.stringify(
      {
        populate: [
          "add_modules",
          "add_modules.text_image_block",
          "add_modules.text_image_block.image",
          "add_modules.list_values",
          "add_modules.list_values.image",
          "add_modules.faq_list",
        ],
      },
      {
        encodeValuesOnly: true, // prettify URL
      }
    );

    const fetchData = await fetch(`http://localhost:1337/api/pages?${query}`);
    const res = await fetchData.json();
    setData(res?.data[0]);
  };
  useEffect(() => {
    getData();
  }, []);

  console.log(data, "dddd");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <BannerComponent bannerData={data} />
      <ModulesBlock moduleData={data?.attributes?.add_modules} />
      <Footer />
    </>
  );
}
